lib/init.coffee, lib/linter-view.coffee, lib/statusbar-summary-view.coffee, lib/statusbar-view.coffee, spec/linter-view-spec.coffee, spec/statusbar-view-spec.coffee, stylesheets/gutter.atom-text-editor.less, stylesheets/highlights.atom-text-editor.less, stylesheets/statusbar-summary-view.less
When styling markers and a line has multiple messages, choose the message
with the level of highest precedence.
Default view:
ShowInfoMessages turned on:
=> Add support for message level 'info'.

lib/linter.coffee
Fixes #389 
The function getUri() is called on @editor, however, this function does not seem to exist. Changed to getPath().
=> Fix crash on load

lib/init.coffee
Let's talk about the new default configuration.
Should we keep the old one?
I really like the new inline view but the status bar becomes a little bit useless if the inline view is displayed ; except if you `Show all errors` in the status bar, that's why I put this configuration by default in the commit.
=> Default configuration

lib/init.coffee
This follows the first suggestion on
https://discuss.atom.io/t/how-to-speed-up-your-packages/10903.
Previous to this diff, `linter` would take over 200ms to load on my
machine, according to Timecop. Now when I run:
atom.packages.getLoadedPackage('linter').loadTime
I consistently see `linter` loading in under 10ms (it's usually <5ms).
Activation time has not seemed to increase dramatically as a result:
atom.packages.getLoadedPackage('linter').activateTime
Seems to hover around 80ms.
I can probably do even better in follow-up diffs.
=> Push top-level require() calls down into the functions that use them.

lib/init.coffee
This makes it possible to remove a dependency on `lodash` in `init.coffee`.
Curiously, this was my first justified use of the
[Embedded JavaScript](http://coffeescript.org/#embedded) feature in
CoffeeScript because I needed to use the ES6 iteration idiom for `Set`,
for which there is no equivalent in CoffeeScript.
This also updates `deactivate()` to null out references so they can be garbage collected.
This is good practice if a package toggles between activated and deactivated.
=> Change linterViews to be an ES6 Set rather than an Array.

lib/linter-view.coffee, lib/linter.coffee, package.json
Both `CompositeDisposable` and `Emitter` are available on `require('atom')`.
I even made sure that `require('event-kit').Emitter === require('atom').Emitter`
was `true`.
=> Remove event-kit dependency.

lib/linter-view.coffee
Decorations of `type: 'gutter'` have been renamed to `type: 'line-number'`.
=> Replace deprecated type

lib/linter.coffee
Defers the loading of lodash and XRegExp until they are used.
Replaced _.memoize() with custom logic to pave the way to removing
the lodash dependency altogether in Linter.
The only other top-level `require()` calls that could be eliminated
are for `log` and `warn`.
One thing that I found a little odd is that, assuming `@executablePath`
never changes over the lifetime of the `Linter` once it is set,
`@_statCache` will only ever have one entry in it.
=> Make Linter load faster since all clients need to load this class.

lib/init.coffee, lib/linter-view.coffee
Perhaps this was undesired behavior for most, but I loved the way that sublime-linter would clear out the errors as soon as you started typing.
This change brings that feature to AtomLinter behind an off-by-default setting "Clear On Change".
=> support clearing warning on change

README.md
In reference to Issue #413, as I published that linter today.
=> Added Reek linter to Ruby section of README

lib/linter.coffee
Gives subclasses a chance to read or change the command, args and options, before creating new BufferedProcess while lintFile.
This is a backward compatible improvement.
Closes #289
PS: I'a a newbie of CoffeeScript .
=> Add public method beforeSpawnProcess: (command, args, options) to Linter

lib/init.coffee, lib/linter.coffee, package.json
The user is prompted the first time a missing executable is detected
and given the option of fully or partially ignoring further warnings.
If warnings are partially ignored, a small notification will be
displayed at the bottom of the editor each time a missing executable
is detected.
=> Handle missing linter executable

styles/highlights.atom-text-editor.less
When line height is increased from the standard line height, wavy underlines were repeated vertically causing duplicate lines.
=> :bug: Fix wavy underline with non-standard line height #427

lib/linter.coffee
Previously it didn't look like `baseOptions` was actually iterated over, since `executionTimeout` was hard-coded in there.
This pull request addresses that and also adds a helper method so that `baseOptions` and `options` use the same path.
=> Iterate over base options

CHANGELOG.md, lib/legacy.coffee
Fixes #596 
@iam4x Will you try this branch and see if it fixes the problem? I can't reproduce it.
My best theory is that because `fs.write` and `fs.close` are both asynchronous it sometimes closes the file before it finishes writing. I don't know if running Linux or maybe having an SSD causes me to not run into this problem.
=> Try using writeSync and closeSync

CHANGELOG.md, lib/commands.coffee, lib/editor-linter.coffee, lib/linter-views.coffee, styles/linter-plus.less
I add a command to set the bubble transparent. This can be be mapped to a key. On the next keyup event the bubble is set opaque again.
```
'atom-text-editor:not(.mini)':
'ctrl': 'linter:set-bubble-transparent'
```
This was discussed here: #608
=> Add command set-bubble-transparent

CHANGELOG.md, lib/views/bottom-status.js
Rename the `Errors` text on the status line to `Issues`. When there are only info or warning level items, it's a bit alarming to the user to call them errors.
I see there's another PR in this space, but I wanted to throw this out there as a pretty small delta to the current UI.
=> change the 'Errors' text to 'Issues'

CHANGELOG.md, lib/linter-views.coffee
Change the `Current File` tab title to just `File`. This matches the `Project` tab a bit better, and is more terse - status bar space is at a premium :)
=> change 'current file' text to just 'file'

lib/commands.coffee, lib/editor-linter.coffee, lib/linter-plus.coffee, lib/linter-views.coffee, spec/legacy-spec.coffee
Linter Plus originally started out by copy/pasting code from my atom-hack and wrapping it in services, It's codebase was quite rough. So this is the Plan I followed to fix it.
- Prefix internal properties
- By doing the step above, we had to replace a lot of direct changes into other module's properties with observers and setter/getters
- Remove the prefixes added in first step
This is the last step of the Plan.
/cc @joefitzgerald
=> Remove underscores from the CodeBase

lib/commands.coffee, lib/views/message.coffee, lib/views/multiline.coffee, styles/linter-plus.less
Support for multiline messages
For reasons of backwards-compatibility, multiline messages need to have `multiline: true` field set. With `multiline: true`, `text` argument will be treated with `white-space: pre`. If `html` is set, it takes precedence over both (since I'm not entirely convinced if "multiline html" even makes sense).
Multiline messages are collapsed to show only first line by default. It is possible to expand those individually with mouse click (at any given moment, only one message can be expanded this way), or all with `linter:expand-multiline-messages` command, preferably bound to a key (`ctrl` or `shift`, for example).
For styling, there are two options I could think of. Current implementation looks something like this:
Collapsed
Panel message expanded
Tooltip message …
=> Multiline messages

CHANGELOG.md, lib/editor-linter.coffee, lib/linter-views.coffee, lib/main.coffee, styles/linter-plus.less
I added a third tab to the bottom which lets you filter the messages in the panel to show only error of the current line.
This is still work in progress. But I would like to know what you guys think of this idea.
Fixes #587.
=> Add tab to show only errors in current line

CHANGELOG.md, lib/editor-linter.coffee, lib/linter-plus.coffee, lib/linter-views.coffee, lib/main.coffee, lib/views/bottom-tab.js, styles/linter-plus.less
Follow up to #637
Fixes #654
/cc @josa42 
Things that could've been avoided in that PR
Josa42: Thank You again for your PR :bow: , We greatly appreciate your contributions. It would've been ideal to have those issues addressed in your PR but it's still cool.
New Changes
=> Refactor Views codebase

CHANGELOG.md, lib/main.coffee
Ref: https://github.com/AtomLinter/Linter/issues/510
=> Catch require time errors thrown from legacy providers

CHANGELOG.md, styles/linter-plus.less
- tweak the alignment of the status line tab so that they're more centered in the status line
before:
after:
=> align the status items using vertical-align: middle

lib/linter-views.coffee
OK, I'm trying to do my homework and to contribute more actively to this plug-in, not only asking but also giving back something! :smile: 
It seems that the problem has been addressed also by Atom guys: 
https://github.com/atom/atom/issues/4834
they added [a note in workspace.coffee](https://github.com/atom/atom/blob/f73d3df2339bd2ec6017e156dbc5edadf2b9c18b/src/workspace.coffee#L670) that says:
> If your panel changes its size throughout its lifetime, consider giving it a higher
priority, allowing fixed size panels to be closer to the edge. This allows control targets to
remain more static for easier targeting by users that employ mice or trackpads.
Attached you'll find a PR with the change.
=> Changed priority of the bottom panel, fixes #668

styles/linter-plus.less
Badges in the tooltips overflow outside their colored box. This at least prevents that, but perhaps it could be improved further by making sure the badge grows with its content.
=> prevent badge overflow

CHANGELOG.md, lib/editor-linter.coffee, lib/helpers.coffee, spec/fixtures/test.txt, spec/helpers-spec.coffee
I'm not done with this yet. But it's time for this to have some exposure.
I've created a `linter-ruby` example, which I might just merge into `linter-ruby` later.
```coffee
module.exports = LinterRuby =
config:
rubyExecutablePath:
default: 'ruby'
type: 'string'
activate: ->
atom.notifications.addError(
'Linter package not found.',
{
detail: 'Please install the `linter` package in your Settings view'
}
) unless atom.packages.getLoadedPackages 'linter'
provideLinter: ->
regex = '(?<file>.+):(?<line>\\d+):\\s(?<type>(?:\\w+(?:\\s)?)(?:error|warning))(?:,\\s)?(?<message>.+)'
command = "#{atom.config.get('linter-ruby.rubyExecutablePath')} -wc"
provider =
scope: 'file'
lintOnFly: false
grammarScopes: ['source.ruby', 'source.ruby.rails', 'source.ruby.rspec']
lint: (activeEditor, helpers) ->
file …
```
=> Create Helpers for Easy CLI Linter Creation.

lib/editor-linter.coffee, lib/helpers.coffee, spec/buffer-modifying-provider-spec.coffee
Fixes https://github.com/AtomLinter/Linter/issues/696
I've confirmed that it works.
Buffer modifying linters need to have a `modifiesBuffer:true` in their object. This change is backward compatible.
=> Support buffer modifying linters

keymaps/linter.cson
Also `alt-<` is not taken and easy to reach on US and german layouts. It could be used for going to the previous error, but I think that functionality was removed and has to be reimplemented.
Fixes #667
=> :new: Use alt-> to jump to next error

CHANGELOG.md, lib/linter-views.coffee
Just like the title says. We were leaking a marker, that would slow the text editor over time.
Ref: #708
=> Fix bubble marker leak

coffeelint.json
This PR simply replaces the contents of coffeelint.json with the contents from https://github.com/atom/atom/blob/92e495db6880c3c26c5afd2953550ff27043edcd/coffeelint.json. This is done to match the core team's style guide.
=> Update coffeelint.json With atom/atom's Version

keymaps/linter.cson
It has passed more than 20 days by now of #648 report and It shouldn't be acceptable that the plugin break atom keybinding in such way for too long, I'm sending a PR commenting the keybinding on the plugin as a temporary workaround until we get a proper fix.
=> :fire: Comment 'alt' keybinding as a workaround to #648

lib/helpers.coffee, lib/validate.coffee, spec/helpers-spec.coffee
Because it's simple and dependable
In the future PRs I'll be implementing efficient markers
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/785)
=> Use JSON as message key

lib/helpers.coffee
Atom-Linter module at the moment throws stringish errors, I am gonna fix this in that module as well. But thought we should be handling this scenario
=> Allow stringish errors

lib/linter-views.coffee, lib/main.coffee, spec/ui/bottom-panel-mount-spec.coffee
Just reverted the `statusIconPosition` setting from e36281e3d4e8cfdae29c71ac790ebdfb1ae58030 and updated the attach function since there is only one container now. Additionally, the dynamic priority assures the tile will snap to the corresponding side.
Fixes #720 and resolves the regression in #575, #576, #630
Thanks for your time!
=> Reverted ability to select status-bar side

CHANGELOG.md, styles/linter-plus.less
Line up the baseline of the text inside the two bottom tabs with the text outside it.
Screenshot of change shown below, with an XScope horizontal guide to show the alignment
=> fix text baseline alignment on bottom bar

styles/linter-plus.less
Fixes https://github.com/atom-community/linter/issues/876
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/879)
=> Fix extra padding in panel when there's no messages

styles/linter-plus.less
Under recent versions of Atom setting margins or font sizes in the butter will cause alignment issues
This fixes that ... The dot was kinda large anyway, so I think it looks better now
=> Fixed gutter corruption on Atom 1.0.13 - And looks better

lib/editor-linter.js, lib/editor-registry.coffee, lib/linter-views.coffee, lib/linter.coffee, spec/common.coffee, spec/editor-linter-spec.coffee, spec/editor-registry-spec.coffee
Features:
- Markers will be available in different editors at the same time
- Everytime a tab is switched, we remove all the markers from previous tab and re-add all the markers in new tab, keeping them in both would mean no unnecessary operations.
- more that I can't think of right now
This does come at a speed regression. I'll be fixed it afterwards.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/899)
=> Handle markers in editor-linter

CHANGELOG.md, lib/ui/message-element.js, styles/linter-plus.less
Fixes #893. Related to #892 and #859.
On a related note, I did not find any output of the `multiline` class so this is purely the CSS fix.
=> Fix linter message styles

CHANGELOG.md, lib/linter-views.coffee, lib/ui/message-element.js, styles/linter-plus.less
Here's an alternative keeping the text inline with the flow (meh):
Here's the current PR (same behaviour as before, but text will continue flowing below):
And before (with bubble link):
=> Disable path in bubble and improve link/text flow

styles/linter-plus.less
Our plugin generates errors, warnings, and info level analysis issues. We'd like to be able to call them that in the UI; currently we use `Error`, `Warning`, and `Trace` in order to get css styling in the editor for info level events. This PR adds `info` as a synonym for `trace`.
=> use info as a style key, as well as trace

styles/linter-plus.less
Remove a css `top:` offset. This seemed to be causing the linter status line contribution to be slightly off-center. I'm not sure if this is intentional or an artifact of some refactoring -
before:
after:
=> remove css top offset

CHANGELOG.md, lib/ui/bottom-panel.js
Fix https://github.com/atom-community/linter/issues/909 - made the text in the bottom panel selectable.
=> made the text in the bottom panel selectable

CHANGELOG.md, lib/main.coffee, lib/ui/bottom-panel.js, lib/ui/message-element.js, spec/commands-spec.coffee, spec/linter-behavior-spec.coffee, spec/ui/bottom-panel-spec.coffee, styles/linter-plus.less
Adds two options for controlling panel size - `errorPanelHeight` and `alwaysTakeMinimumSpace`. The error panel height can be manually configured, or automatically updated by using the drag feature  (results in persistence of height). The minimum space option is a toggle which causes the height of the panel to equal `min(height option, messages height)` (vs `height option`). This patch also closes an issue where the linter panel would stay open with no messages visible.
Closes #928
**Empty Linter Panel Issue:**
Edit: Had to modify tests to set-up visibility before checking (not visible by default when there's no error messages anymore).
=> Improve error panel sizing behaviour

CHANGELOG.md, lib/linter-views.js
Fix an issue where `linter.displayLinterInfo` was not respected. The bottom status bar was reset to visible irrespective of the user's preference -
=> fix an issue where linter.displayLinterInfo was not respected

lib/validate.coffee, spec/validate-spec.coffee
I have seen somebody add both fields, they are a violation of the API and neither future-safe nor documented anywhere. They should be reported as an error
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/975)
=> Stricter message validation

lib/indie-registry.js
Thank you for making a really simple API!
I'm using it for something non-lint-related ([GitHub Pull Requests](https://atom.io/packages/pull-requests) package) and except for this typo, it worked surprisingly well!
Also, where in [atomlinter.github.io/providers.yml](https://github.com/AtomLinter/atomlinter.github.io/blob/master/_data/providers.yml) should I add a link to [GitHub Pull Requests](https://atom.io/packages/pull-requests)? `Generic Linters / Writing Assistance` or `Generic Linters / Project Organization` or some other place?
Screenshot:
=> typo when registering with indie-registry

benchmarks/common.js, benchmarks/message-registry.js
Just like the title says
The way I run them is that I run atom in spec runner mode in package root, then open it's dev console and paste this 
```
require('/home/steel/.atom/packages/linter/benchmarks/message-registry.js')
```
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/1024)
=> Add message registry benchmarks

lib/message-registry.js, spec/message-registry-spec.js
I believe this to be the reason for https://github.com/atom-community/linter/issues/1090
and the crashes @Arcanemagus is experiencing
After this, there is no known bug in message-registry :tada: :tada: :tada: :tada:
=> Fix a bug in message registry

lib/helpers.js, lib/message-registry.js, lib/types.js, lib/validate.js, spec/message-registry-spec.js, spec/validate-spec.coffee
It has limited set of values, these are case sensitive, `error`, `warning` and `info`
They are not shown to the user but used for other internal purposes, we might even use these to paint the messages so the providers don't have to provide style for each message type.
Another benefit of having this attribute is that we can show in the UI how many are warnings and how many are infos
Fixes #878
=> Add severity attribute

CHANGELOG.md, lib/linter-registry.js, package.json, spec/config-spec.coffee, spec/linter-registry-spec.coffee
Setting this enabled by default because that's the current behavior.
=> Add config to lint preview tabs

package.json
Hi,
Per title this pull request should resolve #1163 and it would be nice if you could publish this edit once you accept this pull request by running:
```bash
apm publish patch
```
This way I can more easily use this fix when I build Atom on Arch Linux with this package pre-installed. 
Thanks for your time,
Brenton
=> Adding coffee-script devDep to package.json, along with readme: field, hence fixing #1163

lib/linter-views.js
`src/linter-view.js`'s `renderBubble` skips refreshing the tooltip when the cursor is within the currently shown tooltip's range. However the tooltip should get fully refreshed without skipping anything when its current message has been removed.
Here is an example of a situation when a stale tooltip is shown (using the current master 9338d172) even when the error it's showing gets fixed:
After the changes in this pull request the same situation looks like this:
The pull request tries to simplify internal state handling a bit (YMMV) by keeping all info related to the current tooltip in a single property called `bubble`. The property should be `null` when the tooltip is not shown. When the tooltip is shown then `bubble` should be an object containing all the relevant info (currently shown …
=> Refresh the tooltip when its current message gets removed

.travis.yml, package.json
We still consume legacy linters (1.x) with semver so it shouldn't be a breaking change
=> Consume API providers by fixed versions only

lib/index.js
It's Indie Registry v2 and nobody is using it because it's unreleased so this change doesn't break anything
=> Simplify export signature of IndieRegistry

lib/index.js, package.json
Pretty straight forward. Allows people to disable auto-install of linter-ui-default on boot.
=> Add installRecommendedPackages config

lib/editor-linter.js
They would be triggered on editor open without even changing anything. This fixes that behavior
I tried to add a spec, but wasn't able to repro the bug in spec window. I suppose it happens in the first place because of some internal atom bug or something. In any case, I've added a note above the fix to make sure it's not deleted in some refactoring
=> Fix an inconsistent behavior bug with on change providers

docs/examples/indie-linter-v2.md, docs/examples/standard-linter-v2.md, docs/examples/ui-provider-v1.md, docs/guides/upgrading-to-indie-linter-v2.md, docs/types/indie-linter-v2.md, docs/types/linter-message-v2.md, docs/types/standard-linter-v2.md, docs/types/ui-provider-v1.md
Clean up the look of the Markdown itself by using reference links where possible.
=> Use reference links

docs/examples/indie-linter-v2.md
=> Update indie-linter-v2.md: Fix `Message.location` to contain `file`, not `path`.

.eslintrc.json, lib/editor-registry.js, lib/greeter/index.js, lib/index.js, lib/indie-registry.js, lib/linter-registry.js, lib/main.js, lib/message-registry.js, lib/toggle-view.js, lib/ui-registry.js, spec/main-spec.js
Defer as much as possible for later work and/or only when necessary, allowing the package activation time to be majorly reduced.
On my "pristine" profile (`linter`, `linter-ui-default`, `linter-eslint`, `intentions`, `busy-signal`) this brings activation from an average of 111.7 ms down to 8.3 ms. 🎉
Fixes #1026.
=> Reduce activation time

spec/editor-linter-spec.js
Instead of relying on timing and bad counting, make the spec truly async and properly count the number of invocations.
=> Make EditorLinter::onShouldLint spec async

docs/types/linter-message-v2.md, lib/helpers.js, lib/validate/index.js, spec/helpers-spec.js, spec/validate-spec.js
This PR allows providers to override the displayed `linterName` on a per-message level.
I added a spec as well as a validator+spec.
Released under CC0.
Closes #1485
=> Allow messages to override the linterName (in v2)

CHANGELOG.md, lib/helpers.js
Fix issue where a lint message description changes but the excerpt, range, etc do not change and so the message does not update (https://github.com/nwolverson/atom-ide-purescript/issues/164).
(This also seems to occur if I call `clearMessages` prior to adding the updated message)
=> Include description in message key

lib/editor-linter.js, lib/main.js, spec/editor-linter-spec.js
This addresses the issue described in #1510 
This first gif shows the current behaviour, the two JS editors are for the same file. Notice how the linting errors in the bottom now longer show up when focusing the editor at the top.
This second gif shows the new behaviour, the two JS editors are for the same file. Notice how the linting errors in the bottom still show up when focusing the editor at the top.
I'm not sure if the implementation I chose is desired. My reasoning behind it is that the information (`thereIsAnotherEditorForTheSameFile`) might be useful in other scenarios as well. Alternatively the check for other buffers can be performed in the [deleteByBuffer](https://github.com/steelbrain/linter/blob/1f9efea649c43ab50097d6ddc0d1e9685ee28413/lib/message-registry.js#L136) in the …
=> Don't wipe messages for file if it is opened multiple times

lib/linter-registry.js
It's probably easier for a user to open the console by the click of the button, rather than providing a description where to find a toggle to do so.
=> Add button to open Console

lib/helpers.js, lib/linter-registry.js, spec/helpers-spec.js
Fix calls to `Linter: Debug` on editors that don't have a path (no saved file), returning that they are ignored.
=> Handle editors with no path in debug call

lib/helpers.js, lib/message-registry.js, package.json, spec/common.js, spec/message-registry-spec.js
This updates the way messages are filtered. The previous code was not flagging messages as added, removed, or kept correctly. A highly optimized algorithm is written to do the diff checking.
It greatly improves the performance of linter by not sending messages that are already rendered to linter-ui. 
Fixes https://github.com/steelbrain/linter-ui-default/issues/580
Fixes https://github.com/steelbrain/linter/issues/1709
=> Rewrite diff check algorithm + improve performance + fix linter fixes 

README.md
Add instructions in the README to prompt user to install the linter-ui-default package if it's not auto-installed.
As a newbie Atom user, I went ahead and installed the linter and code package like all the docs and guides stated.  It took longer than I'd like to admit to find closed Issue #1712 which indicated that the UI package needed to be installed too.
Hope this little addition helps someone else down the line.  Of course, feel free to tweak as you see fit - or let me know if this is something that shouldn't have arisen.  Thanks!
=> chore: mention linter-ui-default dependency

spec/main-spec.js, spec/message-registry-spec.js
There are small typos in:
- spec/main-spec.js
- spec/message-registry-spec.js
Fixes:
- Should read `invalidates` rather than `invaildates`.
- Should read `initialize` rather than `initialze`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos
