- lib/linter-view.coffee
- lib/statusbar-view.coffee
- package.json
- spec/linter-view-spec.coffee
@dmnd, fixes issue with space pen version rolling forward.  Also corrects a couple deprications that slipped through.
> Fix deprication in space pen ussage

- README.md
> Unify Appearance of Read Me Shields

- lib/init.coffee
- lib/linter-view.coffee
- lib/statusbar-summary-view.coffee
- spec/linter-view-spec.coffee
- stylesheets/statusbar-summary-view.less
So it display the number of errors/warning.
Let me know if you need further information about the commit.
See: https://github.com/AtomLinter/Linter/issues/242
> Status bar summary

- README.md
I have add a linter-luacheck package for Lua.
> Add link to linter-luacheck for Lua.

- README.md
Which now defaults to message level "info" :grinning:
> Update readme, add linter-pep257

- images/wave.svg
- stylesheets/highlights.atom-text-editor.less
Previous highlights on dark background:
New highlights on dark background:
Previous highlights on light background:
New highlights on light background:
> More visible highlights

- lib/init.coffee
restoreDefault has been replace by unset, fixes #414 and fixes #436
> Replace deprecated call

- Gruntfile.coffee
Missed the Gruntfile for issue #409. Side note, anything that can be done about ui-variables.less not being found when linting the stylesheets?
> Missed stylesheets reference in gruntfile

- lib/inline-view.coffee
- lib/linter-view.coffee
Hey,
Maybe my smallest PR ever made, one whitepsace remove, juste to stick the code style rules ;)
> style(code): fixing indent

- lib/linter-view.coffee
- lib/statusbar-summary-view.coffee
- lib/utils.coffee
- stylesheets/statusbar-summary-view.less
Fixed https://github.com/AtomLinter/Linter/issues/402
> Click status bar summary icon to move to error

- lib/init.coffee
- lib/linter-view.coffee
> feat(lintChangeMethod): add options

- README.md
https://atom.io/packages/linter-js-standard
> add `linter-js-standard`

- lib/linter.coffee
see https://github.com/AtomLinter/Linter/issues/489
> child's configuration observe/dispose

- package.json
`linter` has been rewritten and we've done everything we can to maintain backward compatibility. An update should show up in Atom soon and it should just look like a big UI change from a user's perspective.
We still have a lot of work to do with all of the linters. We will migrate all of them to the new API and then we will remove backward compatibility.
Closes #566
Closes #565
Closes #564
Closes #563
Closes #562
Closes #561
Closes #559
Closes #558
Closes #557
Closes #556
Closes #555
Closes #554
Closes #553
Closes #552
Closes #551
Closes #548
Closes #544
Closes #543
Closes #541
Closes #538
Closes #536
Closes #535
Closes #534
Closes #533
Closes #532
Closes #529
Closes #528
Closes #527
Closes #525
Closes #523
Closes #522
Closes #520
Closes #519
Closes #518
Closes #517
Closes #515
Closes …
> linter rewrite

- lib/legacy.coffee
- package.json
Fixes #577
Fixes #578
Fixes #580
> Generate temporary files for legacy linters

- CHANGELOG.md
- lib/editor-linter.coffee
> Ignore lint requests until file is saved somewhere

- CHANGELOG.md
- lib/linter-plus.coffee
- lib/linter-views.coffee
- lib/main.coffee
- lib/views/bottom-tab.js
- styles/linter-plus.less
Just click the active tab to hide it
Click any tab to show it again
Fixes #589
ToDo
> Allow bottom panel to be hidden

- CHANGELOG.md
- lib/commands.coffee
- lib/linter-plus.coffee
- lib/linter-views.coffee
Fixes #588
This PR also lays foundation for Fix of https://github.com/AtomLinter/Linter/issues/496
> Jump to bug on status icon click

- CHANGELOG.md
- lib/commands.coffee
- lib/editor-linter.coffee
> Add Toggle Linters command

- lib/linter-views.coffee
**before**
[![Gyazo](http://i.gyazo.com/28aafe30e68030fa7b2d31ff4c0a7f80.gif)](http://gyazo.com/28aafe30e68030fa7b2d31ff4c0a7f80)
**after**
[![Gyazo](http://i.gyazo.com/1f635a2044ea98041fcf385967b88305.gif)](http://gyazo.com/1f635a2044ea98041fcf385967b88305)
> Fix Marker leak

- CHANGELOG.md
- lib/legacy.coffee
> Use a temporary directory instead of a temporary file

- lib/legacy.coffee
Fixes #604 
A bug introduced by #603
/cc @AsaAyers
> Fix invalid variable reference in legacy

- CHANGELOG.md
- lib/linter-views.coffee
> Fix message rendering for non-editor views

- CHANGELOG.md
- lib/linter-views.coffee
> Make bubble follow cursor

- CHANGELOG.md
- lib/linter.coffee
We already had that error for normal executables, but not for node executables, this PR fixes that and also removes a bunch of redundant non-working code.
Fixes #612
> Show nicer Executable Not Found Error

- lib/legacy.coffee
> Handle error case when providers don't return results

- CHANGELOG.md
- lib/linter-views.coffee
> Deactivate bottom tab when panel is hidden

- CHANGELOG.md
- lib/commands.coffee
- lib/linter-plus.coffee
> Add linter:lint command

- CHANGELOG.md
- lib/linter-views.coffee
- lib/views/bottom-tab.js
Fixes #584
Not hiding the count as discussed. Only hiding project and file buttons.
> Hide StatusBar Icons

- CHANGELOG.md
- lib/linter-views.coffee
Move the status line contribution from the left hand side to the right.
> move the status bar from the left side to the right

- CHANGELOG.md
- lib/linter-plus.coffee
- lib/linter-views.coffee
- lib/main.coffee
> Make underlining optional

- CHANGELOG.md
- lib/main.coffee
> Fix a critical bug in self service

- CHANGELOG.md
- lib/editor-linter.coffee
- lib/linter-plus.coffee
> Render when Project Messages are changed

- CHANGELOG.md
- lib/linter-plus.coffee
> Handle Project Path Changes

- CHANGELOG.md
- lib/linter-views.coffee
> Disabling underline shouldn't disable gutter

- styles/linter-plus.less
> Vertically align text in tabs with rest of status bar

- lib/linter-views.coffee
> Fix tab margin by making sure last tab is set

- CHANGELOG.md
- lib/linter-plus.coffee
- lib/linter-views.coffee
- lib/main.coffee
> Store currently selected tab in package state

- spec/helpers-spec.coffee
In preparation of the expansion of the Helpers for CLIs I've started creating specs for the existing Helpers.
> Spec out the Helpers.

- lib/commands.coffee
- lib/views/bottom-panel.js
Just like the title says
Fixes #672
> Add linter:togglePanel command

- CHANGELOG.md
- lib/linter-views.coffee
- lib/main.coffee
> Add disallowed types config

- lib/linter-views.coffee
- lib/linter.coffee
- lib/main.coffee
- lib/messages.coffee
- lib/views/message.coffee
Some errors thrown from `$ npm run lint`
> style: fix `coffeelint` code style errors

- lib/linter.coffee
Fixes https://github.com/AtomLinter/Linter/issues/687
> Cache MessageRegexp

- lib/linter-plus.coffee
> Messages is no longer a set

- lib/linter-views.coffee
> Make it work without bottomBar

- lib/linter-plus.coffee
Confirmed that it works
/cc @lierdakil
> Hotfix for default state

- CHANGELOG.md
- lib/linter-views.coffee
> Update count on render

- CHANGELOG.md
- lib/linter-views.coffee
> Fix panel visibility

- CHANGELOG.md
- lib/linter-views.coffee
Just like the diff says
Fixes https://github.com/AtomLinter/Linter/issues/710
> Store weak markers

- .eslintrc
- lib/helpers.coffee
- lib/views/bottom-panel.js
- lib/views/bottom-status.js
- lib/views/bottom-tab.js
> :art: fix conding style to match `CONTRIBUTING.md`

- lib/views/message.coffee
- styles/linter-plus.less
> Prevent linter message from wrapping

- lib/linter-views.coffee
- lib/views/bottom-container.coffee
- spec/linter-behavior-spec.coffee
Fixes https://github.com/atom-community/linter/issues/722
> Toggle Panel on double click

- lib/main.coffee
They won't work, just a warning.
/cc @k2b6s9j
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/782)
> Show a warning for depreciated ones

- lib/linter-views.coffee
- lib/message-registry.coffee
- spec/config-spec.coffee
We are no longer filtering messages on get, filtering them on set instead.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/783)
> Cleanup filtering

- spec/editor-linter-spec.coffee
it no longer saves to cwd now, it saves to tmp
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/784)
> Fix a spec that was saving a test file to disk

- lib/linter-plus.coffee
- lib/linter-views.coffee
- lib/message-registry.coffee
- spec/message-registry-spec.coffee
A work in progress at the moment.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/787)
> Efficient updates

- lib/helpers.coffee
> Fix a typo

- lib/main.coffee
- lib/views/bottom-container.coffee
- lib/views/bottom-status.js
- lib/views/bottom-tab.js
- spec/config-spec.coffee
Fixes #683
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/790)
> Status Icon Scope Config

- lib/commands.coffee
- lib/editor-linter.coffee
It was an ordering issue and a typo
Ref: https://github.com/atom-community/linter/issues/748
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/791)
> Fix toggle Linters

- lib/message-registry.coffee
This fixes a race condition with some lazy linters
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/792)
> Only update messages if editor is alive

- lib/helpers.coffee
- lib/message-registry.coffee
- spec/config-spec.coffee
It now runs 10 times per second instead of each animation frame
Fixes https://github.com/atom-community/linter/issues/812
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/813)
> Increase message registry update interval

- CHANGELOG.md
- styles/linter-plus.less
Only show scrollbar when there are scrollable contents.
> Improve linter-panel style

- lib/editor-linter.coffee
- lib/message-registry.js
Just some minor style nits. Nothing new.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/826)
> Style nits

- CHANGELOG.md
- lib/linter-views.coffee
- spec/linter-behavior-spec.coffee
Fixes https://github.com/atom-community/linter/issues/828
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/834)
> Re-apply markers on active pane change

- lib/commands.coffee
- lib/editor-linter.coffee
- lib/editor-registry.coffee
- lib/linter-registry.coffee
- lib/linter-views.coffee
- lib/linter.coffee
- lib/message-registry.js
- spec/editor-linter-spec.coffee
- spec/editor-registry-spec.coffee
- spec/linter-registry-spec.coffee
- spec/message-registry-spec.coffee
Fixes https://github.com/atom-community/linter/issues/829
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/835)
> Make classes disposables

- CHANGELOG.md
- lib/linter-views.coffee
- spec/linter-behavior-spec.coffee
Fixes #830
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/836)
> Fix incorrect behavior of bottom container

- lib/editor-linter.coffee
Fixes #840
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/841)
> [editor-linter] Fix invalid function call

- CHANGELOG.md
- lib/linter-views.coffee
- spec/fixtures/file.txt
- spec/linter-behavior-spec.coffee
refresh it on pane switch
Fixes https://github.com/atom-community/linter/issues/839
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/843)
> Fix bottom container count

- spec/ui/message-element-spec.coffee
Just like the title says
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/846)
> Add specs for message element

- CHANGELOG.md
- lib/linter-views.coffee
- lib/ui/bottom-panel.js
- lib/ui/message-element.js
Fixes https://github.com/atom-community/linter/issues/847
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/848)
> Fix message filePath

- lib/commands.coffee
- spec/commands-spec.coffee
- spec/common.coffee
- spec/config-spec.coffee
- spec/linter-behavior-spec.coffee
- spec/linter-registry-spec.coffee
- spec/message-registry-spec.coffee
Beep Boop.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/861)
> Fix togglePanel command

- CHANGELOG.md
- lib/linter-registry.coffee
- lib/main.coffee
- spec/linter-registry-spec.coffee
Fixes https://github.com/atom-community/linter/issues/779
TODO:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/862)
> Add batchUpdateMessages config

- lib/validate.coffee
- spec/validate-spec.coffee
Fixes https://github.com/atom-community/linter/issues/867
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/868)
> Strict message validation

- CHANGELOG.md
- lib/message-registry.js
- spec/message-registry-spec.coffee
I think this implements what we discussed in #871.  Note that the tests are currently a separate commit since it lets me (and you if you like) easily verify that the current implementation fails the test and that with the fix everything is happy.  I would squash them after addressing any concerns you have prior to requesting final landing.  (Or you can squash them or do whatever you like.)
Please do provide idiomatic guidance on the spec file if it's not to your liking.  I don't do a lot of BDD testing and I worry that I may have done too much prep logic.  (I could see adding more it() cases for the multiple pane case like covering editor deletion, which is why I factored it to be more reusable.)
> Messages per buffer fix

- styles/linter-plus.less
Reverts atom-community/linter#887
> Revert "Fixed gutter corruption on Atom 1.0.13 - And looks better"

- styles/linter-plus.less
Relands #887
Atom folks for some reasons decided to make the scrollbar narrower in the latest version :(
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/890)
> Reland #887

- CHANGELOG.md
- styles/linter-plus.less
> Fix for #859

- CHANGELOG.md
- lib/commands.coffee
- package.json
- spec/commands-spec.coffee
solves this issue: https://github.com/atom-community/linter/issues/894#issuecomment-141783902
> Lint on toggle

- CHANGELOG.md
- lib/commands.coffee
- lib/editor-linter.js
- lib/linter-views.coffee
- lib/main.coffee
- spec/editor-linter-spec.coffee
- styles/linter-plus.less
The API added in #899 is gonna be the base and we're gonna add own our gutter along with a few configurations for them. This will free us from a lot of styling limitations and won't cost much.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/901)
> Add a custom gutter

- CHANGELOG.md
- lib/linter.coffee
- lib/main.coffee
- package.json
Boom :boom:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/905)
> Remove deprecated APIs

- CHANGELOG.md
- lib/main.coffee
- lib/message-registry.js
- lib/ui/message-element.js
- lib/validate.coffee
- spec/validate-spec.coffee
A long awaited and useful feature
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/908)
> Show name of linter

- CHANGELOG.md
- lib/ui/message-element.js
- styles/linter-plus.less
**After:**
**Before:**
Related to #902
> Improve multiline messages and text alignment

- CHANGELOG.md
- lib/ui/message-element.js
- styles/linter-plus.less
> Enable clicking multiline messages + other tweaks

- CHANGELOG.md
- lib/ui/message-element.js
- lib/validate.coffee
- spec/ui/message-element-spec.coffee
- spec/validate-spec.coffee
Beep Boop.
Fixes #922
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/923)
> Allow providers to specify class attribute for messages

- CHANGELOG.md
- lib/ui/bottom-panel.js
- package.json
A long awaited feature :smiley: 
State persistence will be coming soon
Fixes https://github.com/atom-community/linter/issues/880
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/910)
> Make linter panel resizable

- CHANGELOG.md
- styles/linter-plus.less
**Before:**
**After:**
Summary: Uses flexbox and ems to align properly at any scale.
Edit: Updated before images.
> Fix linter gutter alignment cross-theme/zoom

- CHANGELOG.md
- lib/editor-registry.coffee
- lib/linter.coffee
- spec/editor-registry-spec.coffee
Fixes https://github.com/atom/atom/issues/9012
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/930)
> Workaround atom pane issue

- CHANGELOG.md
- lib/editor-linter.js
Dropping the instanceof check as advised by @maxbrunsfeld
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/933)
> Future Safe

- CHANGELOG.md
- lib/editor-linter.js
- spec/editor-linter-spec.coffee
Nobody uses this API, confirmed via github code search.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/934)
> Minor EditorLinter cleanups

- lib/editor-registry.js
Non API breaking change.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/936)
> Simplify EditorRegistry internals

- spec/common.coffee
- spec/editor-linter-spec.coffee
- spec/linter-behavior-spec.coffee
- spec/ui/bottom-container-spec.coffee
Beep Boop.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/943)
> Add more specs

- lib/ui/bottom-panel.js
Fixes #937
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/945)
> Make copy to clipboard work in panel

- .travis.yml
Beep Boop
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/946)
> Tweak travis CI a bit

- CHANGELOG.md
- lib/editor-linter.js
- lib/linter-views.js
Fixes #870
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/947)
> Make bubbles correct

- CHANGELOG.md
- lib/editor-linter.js
- lib/main.coffee
- spec/common.coffee
- spec/editor-linter-spec.coffee
Fixes #952 
ToDo:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/955)
> Add lintOnFlyInterval config

- lib/helpers.coffee
- lib/linter-registry.js
- lib/validate.coffee
- spec/common.coffee
- spec/helpers-spec.coffee
- spec/linter-registry-spec.coffee
- spec/ui/bottom-panel-spec.coffee
- spec/validate-spec.coffee
Beep Boop
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/956)
> Improve linter validation

- lib/linter-views.js
- lib/ui/bottom-panel.js
- lib/ui/message-element.js
- lib/validate.coffee
- spec/ui/bottom-panel-spec.coffee
- spec/validate-spec.coffee
Follow up to #957
Fixes #958
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/959)
> Fix filePath containers for non-open text editors

- CHANGELOG.md
- lib/helpers.coffee
- lib/linter-registry.js
- lib/main.coffee
- spec/config-spec.coffee
Fixes #838 
WIP
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/962)
> Add ignoreVCSIgnoredFiles config

- CHANGELOG.md
- lib/helpers.coffee
- lib/main.coffee
- package.json
- spec/config-spec.coffee
Fixes #968
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/969)
> Implement glob ignoring

- lib/linter-views.js
- lib/ui/bottom-container.js
- lib/ui/bottom-panel.js
- spec/ui/bottom-container-spec.coffee
- spec/ui/bottom-panel-mount-spec.coffee
Beep Beep
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/972)
> Minor tweaks to bottom-container

- CHANGELOG.md
- styles/linter-plus.less
Fixes #978
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/979)
> Fix a styling issue in bottom tabs

- CHANGELOG.md
- lib/main.coffee
- lib/ui/bottom-container.js
- lib/ui/bottom-status.js
- spec/ui/bottom-container-spec.coffee
- spec/ui/bottom-status-spec.coffee
- styles/linter-plus.less
Beep Beep
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/980)
> Add display linter status config

- CHANGELOG.md
- lib/editor-registry.js
- lib/indie-registry.js
- lib/indie.js
- lib/linter.coffee
- lib/main.coffee
- lib/validate.coffee
- package.json
- spec/indie-registry.coffee
- spec/indie-spec.coffee
- spec/linter-indie-api.coffee
See #964 for API
ToDo
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/986)
> WIP: A better self API

- CHANGELOG.md
- lib/linter.coffee
Fixes #988
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/994)
> Notify user when no providers are installed

- CHANGELOG.md
- lib/linter.coffee
I'll be investigating and re-shipping it in the future
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/1001)
> Revert #994

- CHANGELOG.md
- lib/validate.coffee
- spec/validate-spec.coffee
ToDo:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/1005)
> Fix invalid validation

- lib/message-registry.js
- spec/message-registry-spec.coffee
It was added in a PR, reverted accidently, now adding again
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/1017)
> Use buffer as key to store messages

- CHANGELOG.md
- lib/editor-registry.js
- lib/linter-views.js
- lib/linter.coffee
- spec/editor-registry-spec.coffee
Fixes #1007
ToDo
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/1018)
> Make single buffer work across multiple panes

- lib/linter.coffee
- lib/message-registry.js
- lib/validate.coffee
- spec/config-spec.coffee
- spec/linter-behavior-spec.coffee
- spec/linter-indie-api.coffee
- spec/message-registry-spec.coffee
It's a lot more efficient than it used to be, here are some of the key points
- It's optimized when messages are received from a linter for the first time
- It's optimized when no messages change
- It doesn't do anything unless necessary
ToDo
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/1021)
> Enhance message registry

- lib/linter.coffee
- lib/message-registry.js
- lib/validate.coffee
- spec/config-spec.coffee
- spec/linter-behavior-spec.coffee
- spec/linter-indie-api.coffee
- spec/message-registry-spec.coffee
Reverts atom-community/linter#1021
> Revert "Enhance message registry"

- spec/config-spec.coffee
They were working for me and failing for others before, trying to make it work for all of us now
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/1027)
> Fix Specifications

- CHANGELOG.md
- lib/validate.coffee
- spec/validate-spec.coffee
It was required for atom-build, fairly simple change
cc @kepler0
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom-community/linter/1032)
> Support message specific names

- lib/commands.js
- lib/editor-linter.js
- lib/editor-registry.js
- lib/helpers.js
- lib/index.js
- lib/indie-registry.js
- lib/indie.js
- lib/linter-registry.js
- lib/main.js
- lib/types.js
- lib/ui-registry.js
> Flowize linter

- lib/types.js
- package.json
Related to https://github.com/steelbrain/linter-ui-default/pull/62
Reference: steelbrain/linter#1106
> Add selected attribute to message type

- .gitignore
- CHANGELOG.md
- lib/helpers.js
- lib/linter-registry.js
- spec/config-spec.coffee
Fixes https://github.com/steelbrain/linter/issues/1107
> Use Atom core ignore config

- CHANGELOG.md
- lib/linter-registry.js
- spec/config-spec.coffee
- spec/linter-registry-spec.coffee
Fixes https://github.com/steelbrain/linter/issues/1041
> Do not lint preview tabs

- lib/linter-registry.js
- lib/types.js
- lib/validate.js
- spec/linter-registry-spec.coffee
The description of the bug is in the commit message fixing it
> Fix a race condition in using linter results

- lib/helpers.js
- lib/message-registry.js
- spec/message-registry-spec.js
Really hoping it will fix a long standing bug https://github.com/steelbrain/linter/issues/1099
This is a bug, specs confirm it, but not sure if it's exactly that bug
> Fix a bug in message registry

- package.json
Hi,
In this pull request I updated the package.json according to the change in repo ownership.
Thanks for your time,
Brenton
> Change in repo ownership

- lib/types.js
Add ability to have custom apply function in v2 message solutions.
Supports steelbrain/linter-ui-default#113
> Add apply function to solution

- .travis.yml
- lib/helpers.js
- lib/types.js
- lib/validate/index.js
- spec/validate-spec.js
> Icon support for messages

- README.md
- docs/README.md
- docs/examples/indie-linter-v2.md
- docs/examples/standard-linter-v2.md
- docs/examples/ui-provider-v1.md
- docs/guides/upgrading-to-indie-linter-v2.md
- docs/guides/upgrading-to-standard-linter-v2.md
- docs/types/indie-linter-v2.md
- docs/types/linter-message-v2.md
- docs/types/standard-linter-v2.md
- docs/types/ui-provider-v1.md
- lib/types.js
- package.json
Now that our API version 2 is fully finalized and even includes some future proof parameters like icon ( Ref #1224 )
It's time to wrote the docs and made this ready for deployment
Fixes #1130
Todo
> Write API documentation

- docs/examples/standard-linter-v2.md
- docs/guides/upgrading-to-standard-linter-v2.md
- docs/types/standard-linter-v2.md
- lib/helpers.js
- lib/index.js
- lib/linter-registry.js
- lib/types.js
- lib/validate/index.js
- spec/common.js
- spec/linter-registry-spec.js
- spec/validate-spec.js
> Rename lintOnFly to lintsOnChange for API v2

- docs/guides/upgrading-to-standard-linter-v2.md
- docs/types/standard-linter-v2.md
- lib/linter-registry.js
- spec/linter-registry-spec.js
> Re-allow null from providers

- lib/editor-registry.js
- lib/index.js
- lib/indie-registry.js
- lib/linter-registry.js
- lib/main.js
- package.json
- spec/commands-spec.js
- spec/ui-registry-spec.js
> Upgrade to latest ESLint config

- lib/helpers.js
- spec/helpers-spec.js
> Fix support for v1 traces in v2

- docs/examples/indie-linter-v2.md
- docs/types/indie-linter-v2.md
> Minor documentational nits

- docs/README.md
- docs/guides/upgrading-to-indie-linter-v2.md
- docs/guides/upgrading-to-standard-linter-v2.md
The v1 docs have been moved to the repo, remove references to the Wiki.
> Remove reference to the Wiki

- docs/types/linter-message-v2.md
- lib/types.js
Laying foundations for https://github.com/steelbrain/linter-ui-default/issues/131
> Add priority attribute to solutions

- docs/guides/upgrading-to-standard-linter-v2.md
- docs/types/linter-message-v2.md
- lib/helpers.js
- lib/types.js
- lib/validate/index.js
- spec/helpers-spec.js
- spec/validate-spec.js
As discussed with @Arcanemagus
> Minor changes to API and docs

- docs/types/linter-message-v1.md
This is #1302 for v1 branch
Fixes partially #1294
> Document that paths must be absolute

- docs/types/linter-message-v2.md
> Document that paths must be absolute in docs

- lib/editor-linter.js
- lib/editor-registry.js
- lib/helpers.js
- package.json
- spec/editor-registry-spec.js
- spec/helpers-spec.js
> Add lintOnOpen config

- CHANGELOG.md
- styles/linter-plus.less
> Use contrast as text color

- README.md
> Explain installation from settings view

- lib/index.js
- package.json
Also remove a now unnecessary config
> Upgrade to latest package-deps

- lib/commands.js
- lib/helpers.js
- lib/index.js
- lib/linter-registry.js
- lib/main.js
- lib/types.js
- package.json
- spec/commands-spec.js
- spec/common.js
> Add command to show registered providers for current file type

- lib/linter-registry.js
- package.json
- spec/linter-registry-spec.js
> Use the new pending state way

- lib/commands.js
- lib/main.js
- package.json
- spec/commands-spec.js
> Add debug command

- lib/greeter/greet-v2-welcome.js
- lib/greeter/index.js
- lib/helpers.js
- lib/index.js
- lib/linter-registry.js
- lib/main.js
- lib/toggle-view.js
- lib/types.js
- package.json
- spec/commands-spec.js
- spec/common.js
- spec/toggle-view-spec.js
> Add Greeter

- README.md
- docs/README.md
> Prepare docs for v2

- .eslintrc.json
- package.json
I feel bad for having a PR this small, but couldn't slip this in in other PRs because PRs should be focused
> Upgrade ESLint config

- lib/main.js
Another horribly small PR. It sucks to have small, focused PRs but oh well 😛
> Enhance debug command by showing disabled providers

- CHANGELOG.md
- lib/helpers.js
- lib/index.js
- lib/indie-delegate.js
- lib/indie-registry.js
- lib/types.js
- package.json
- spec/indie-delegate-spec.js
- spec/indie-registry-spec.js
A day after the v2 release, better late than never right?!
> Add support for legacy Indie v1 providers

- spec/greeter-spec.js
> Add specs for Greeter

- CHANGELOG.md
- lib/validate/index.js
- spec/validate-spec.js
Fixes https://github.com/atom-haskell/haskell-ghc-mod/issues/208
> Make name optional for v1 again

- CHANGELOG.md
- lib/index.js
This should cleanup settings-view for users
> Unset outdated v1 configs

- CHANGELOG.md
- lib/main.js
- spec/common.js
- spec/main-spec.js
Closes the bug report in my head
> Provide old messages to new UI activations

- CHANGELOG.md
- lib/greeter/index.js
- lib/index.js
- package.json
- spec/greeter-spec.js
> Only show welcome if older configs are present

- CHANGELOG.md
- lib/linter-registry.js
> Add instructions for open dev tools in error message

- CHANGELOG.md
Just noticed while tagging releases
> Make changelog consistent

- CHANGELOG.md
- lib/main.js
> Hotfix Indie API

- lib/linter-registry.js
Just a simple typo, single line change
> Fixed typo in error message

- package.json
> Update flow-bin to version 0.51.1 🚀

- package.json
> Update flow-bin to version 0.53.0 🚀

- docs/types/standard-linter-v2.md
Closes #1572 
@Arcanemagus uh... kinda like this? I mean, it's a trivial change.
> [Docs] Can't return legacy message from v2 provider

- lib/commands.ts
- lib/editor-registry.ts
- lib/helpers.ts
- lib/index.ts
- lib/linter-registry.ts
- lib/main.ts
- lib/message-registry.ts
- lib/toggle-view.ts
- lib/tsconfig.json
- lib/types.ts
- lib/validate/index.ts
This removes a lot of hidden bugs
> TypeScript strict null check

- lib/commands.ts
- lib/main.ts
- spec/commands-spec.js
Free functions are 50% faster due to the overhead of the creation of an object.
https://jsbench.me/g4kjcq9j3s
> fix: make showDebug a free function

- lib/types/linter.d.ts
> Fix word order (#1740) [skip ci]
